server:
  port: 8083
spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: replica2
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://replica1:8082/eureka/
